### ISSUE TITLE
http tags seems missing

### ISSUE THREAD

**Issue by ttys3** [davidB/axum-tracing-opentelemetry#13]
the span create code is:

https://github.com/davidB/axum-tracing-opentelemetry/blob/67f64a6cd474ea9e189bca1649d7389c2c653d99/src/middleware.rs#L146-L163

but I do not see any `http.xxx` in final span.

and `otel.kind = %opentelemetry::trace::SpanKind::Server`, but in the result, I see it is still `internal`

I add a simple `dbg!(&trace_id, &span, &user_agent);` to get the trace_id so I can confirm that the span is created from here.

![image](https://user-images.githubusercontent.com/41882455/187067131-d4471d9f-bb5b-4463-b66f-3d79242eda38.png)

![image](https://user-images.githubusercontent.com/41882455/187067115-fa20dc36-5e0a-438c-919e-e431b3a8f3cf.png)

**Comment by ttys3** [comment]
@davidB  any idea on how to fix this?

**Comment by davidB** [comment]
Since you opened the ticket, I released a new version where "server" was hard-coded.
The similar issue https://github.com/davidB/axum-tracing-opentelemetry/issues/27 was closed because it seems to be a filtering issue on UI.
Reminder inside the process, only the parent span will be tagged as "server" and children span as "internal", if I understand correctly.

Thanks for the reminder, I'll recheck during the coming days.

**Comment by ttys3** [comment]
I did some debug.

seems that `tracing::info_span!`  created span is totally not used.

the used span is created by `create_context_with_trace()`. this is why no tags results

**Comment by ttys3** [comment]
if add some debug code after `remote_span = remote_context.span();`:

```rust
        let mut remote_span = remote_context.span();
        remote_span.set_attributes(vec![
            KeyValue::new("http.host", "xxxx"),
            KeyValue::new("otel.kind", "server"),
        ]);
```
thoses tags did appear.

![image](https://user-images.githubusercontent.com/41882455/197023401-6758f50e-0318-4806-a3ac-976f3abc3378.png)

**Comment by ttys3** [comment]
so there's 2 issue:

1. tracing::info_span! created span is totally not used.
2. this new created span is standalone, and can not work with tracing instrument and could not be a parent span. this is useless

**Comment by davidB** [comment]
Thanks for your investigation. Do you want to make a PR?
Else I'll try to fix it (+ some other requests) next week-end.

**Comment by davidB** [comment]
From my test, the issue is info are not attached to the first span but to the child (aka 2 opentelemetry span are created)

![2022-10-23-202133_911x893_scrot](https://user-images.githubusercontent.com/10675/197409067-3342c8ba-01e1-4abd-b2cf-f75ab8697f87.png)

**Comment by davidB** [comment]
this internal span is not created when the client request already have a trace. So I guess the issue is caused by the current HACK of create_context_with_trace where a "fake" opentelemetry span is created to initiate the trace (and have a trace_id).

**Comment by davidB** [comment]
I released a version 0.5.1. Can you give a try (from my test no longer creation of fake internal span)

**Comment by ttys3** [comment]
I tried this release and the problem still exists.
I can not find the reason.

I 'll try to make a small demo to reproduce this when I have time.

thank you for the support.
